#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.4.2"
  namespace: tap-install

  registry:
    host: tapbuild.azurecr.io
    repositories:
      buildService: tap/build-service
      ootbSupplyChain: tap/supply-chain