apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-install-gitops
  namespace: tap-install-gitops
  annotations:
    kapp.k14s.io/change-group: tap-install-gitops/app
    kapp.k14s.io/change-rule: "upsert after upserting tap-install-gitops/rbac"
spec:
  serviceAccountName: tap-install-gitops-sa
  fetch:
  - git:
      url: https://github.com/ynamadi/tap-run
      ref: origin/projectscions
      secretRef:
        name: tap-install-gitops-github
  template:
  - ytt:
      paths:
      - config
      - config-run
      - config-proxy
      valuesFrom:
      - configMapRef:
          name: tap-install-gitops
      - secretRef:
          name: tap-install-gitops
  deploy:
  - kapp: {}
