#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: y-compiles.com
  namespace: tanzu-system-ingress
spec:
  commonName: '*.staging.tap.tanzu.y-compiles.com'
  secretName: tls
  issuerRef:
    name: letsencrypt-http01-issuer
    kind: ClusterIssuer
  dnsNames:
  - '*.staging.tap.tanzu.y-compiles.com'
---
apiVersion: v1
data: #@ data.values.tap.credentials.certificate
kind: Secret
metadata:
  name: tls
  namespace: #@ data.values.tls.namespace
type: kubernetes.io/tls
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: contour-delegation
  namespace: #@ data.values.tls.namespace
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting tap-install/tap"
spec:
  delegations:
    - secretName: #@ data.values.tls.secretName
      targetNamespaces:
        - "*"